name: fb2converter release

on:
  create:
    tags:
    - "v1.8.1"
  push:
    branches: [ "master" ]
    tags:
    - "v1.8.1"
    
permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
 
    - name: Ubuntu version
      run: lsb_release -a

    - name: Download dictionaries
      run: |
        cd static/dictionaries
        wget -r -l1 --no-parent -nd -A.pat.txt http://ctan.math.utah.edu/ctan/tex-archive/language/hyph-utf8/tex/generic/hyph-utf8/patterns/txt
        wget -r -l1 --no-parent -nd -A.hyp.txt http://ctan.math.utah.edu/ctan/tex-archive/language/hyph-utf8/tex/generic/hyph-utf8/patterns/txt
        for a in $(ls *.txt); do gzip $a; done
        ls -lah

    - name: Download sentences
      run: |
        cd static/sentences
        curl -L https://api.github.com/repos/neurosnap/sentences/tarball | tar xz --wildcards '*/data/*.json' --strip-components=2
        for a in $(ls *.json); do gzip $a; done
        ls -lah

    - name: Get latest CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latest
        ninjaVersion: latest

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build - win32
      env:
        MSYSTEM_NAME: win32
      run: |
        cmake -G Ninja -B build_win32
        cmake --build build_win32 --target release

    - name: Build - win64
      env:
        MSYSTEM_NAME: win64
      run: |
        cmake -G Ninja -B build_win64
        cmake --build build_win64 --target release

    - name: List results
      run: ls -lah fb2c_*

    - name: Tag the repository
      id: tag
      run: |
        TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
        echo "$TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
        git push origin $TAG

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          fb2c_*.zip

